name: validatorless
description: This package provides a means to validate text inputs on the flutter and was inspired by Yup
version: 0.0.3
author: Thiago
homepage: https://github.com/othiagobruno/validatorless

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: